name: Deploy CDK Application

on:
  push:
    branches:
      - main

jobs:
  production-deployment:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::122610492874:role/GitHubActionsOIDC-DeployProductionRole
          aws-region: us-east-1

      - name: Install Dependencies
        run: npm install

      - name: CDK Deploy Production
        run: npx cdk deploy GymGuruApiStack-production --require-approval never -c stage=production